const jokeEl = document.getElementById("joke");
const jokeBtn = document.querySelector(".jokerbtn");

window.addEventListener("DOMContentLoaded", () => {
  if (jokeBtn) {
    jokeBtn.addEventListener("click", generateJokes);
  }
});




const jokes = [
  "Why did the creeper go to school? Because it wanted to explode its knowledge!",
  "What do you call a Minecraft player who's always dying? A respawn specialist.",
  "Why don't Minecraft players ever get lost? Because they always follow the North Star... or a compass.",
  "How do Minecraft villagers stay in shape? They do squat thrusts in the trading halls!",
  "Why did the Enderman apply for a job? He wanted to take blocks seriously.",
  "What's a skeleton's favorite weapon in Minecraft? A bow and arrow—it's his bread and butter!",
  "Why do zombies love Minecraft? Because they get to play the game of the living dead.",
  "What did the diamond say to the coal? You're not as valuable as me!",
  "Why don't Minecraft spiders ever win at hide and seek? Because they always leave a web of evidence.",
  "What do you call a Minecraft house made of TNT? An explosive personality!",
  "Why did the Minecraft player bring a ladder to the bar? He heard the drinks were on the top shelf!",
  "How do you know if a creeper is happy? It's about to explode with joy!",
  "Why did the slime go to the gym? It wanted to get in shape!",
  "What's the difference between a Minecraft player and a builder? One is just starting to mine!",
  "Why do Minecraft cows always look worried? Because they know they might become steak!",
  "What do you call a Minecraft player with no arms? An armless builder!",
  "Why did the Minecraft player quit his job? He wanted to pursue his mining career!",
  "How many Minecraft players does it take to change a light bulb? None, they just place torches everywhere!",
  "Why don't Minecraft zombies ever win arguments? Because they're always falling apart!",
  "What's a Minecraft player's favorite type of music? Block and roll!",
  "Why did the Enderman move to the Nether? He wanted a change of scenery!",
  "How do you organize a Minecraft party? You invite everyone to the server!",
  "Why do Minecraft players make good friends? Because they always have your back when you're mining!",
  "What did one block say to another? Let's stick together!",
  "Why did the Minecraft player bring string to the party? Because he wanted to tie one on!",
  "What's a Minecraft chicken's favorite instrument? The drum stick!",
  "Why do Minecraft players never need a map? Because they always know which way is north!",
  "How do you know if a Minecraft player is sleeping? They stop mining!",
  "Why did the Minecraft player bring a pickaxe to the concert? Because he wanted to rock out!",
  "What do you call a Minecraft player who builds underwater? A sub-contractor!",
  "Why don't Minecraft bats sleep during the day? Because they're already hanging around!",
  "What's a Minecraft player's favorite type of pizza? One with extra blocks!",
  "Why did the Minecraft player become a gardener? Because he wanted to grow on trees!",
  "How do Minecraft players stay cool in the summer? They go to the ice biome!",
  "Why did the Minecraft creeper wear a watch? Because he wanted to explode on time!",
  "What do you call a Minecraft player who's always broke? A poor miner!",
  "Why do Minecraft players make terrible comedians? Because all their jokes are block-buster failures!",
  "What's a Minecraft player's favorite dance move? The block and roll!",
  "Why did the Minecraft player bring a helmet to the library? Because he was mining for knowledge!",
  "How do you make a Minecraft player laugh? Tell him a joke about blocks!",
  "Why do Minecraft zombies never win at poker? Because they always show their hands!",
  "What did the Minecraft player say when he found diamonds? This is un-be-leaf-able!",
  "Why don't Minecraft skeletons ever feel cold? Because they don't have the guts to admit it!",
  "What's a Minecraft player's favorite sport? Mining!",
  "Why did the Minecraft player go to the doctor? Because he was feeling block-headed!",
  "How do Minecraft players stay motivated? They keep their eyes on the prize... block!",
  "Why do Minecraft players never get lonely? Because they always have blocks around them!",
  "What do you call a Minecraft player who's afraid of heights? A ground hugging builder!",
  "Why did the Minecraft player become an architect? Because he wanted to build a career!",
  "What's a Minecraft player's favorite TV show? The Block!",
  "Why do Minecraft pigs never go swimming? Because they don't want to become pork chops!",
  "How do you know if a Minecraft player is smart? They always think outside the box... I mean block!",
  "Why did the Minecraft player bring a flashlight to the cave? Because he wanted to see the light at the end of the tunnel!",
  "What do you call a Minecraft player who builds castles? A block-builder!",
  "Why do Minecraft players never win at chess? Because they're always thinking in blocks!",
  "What's a Minecraft player's favorite snack? Pixel-flavored chips!",
  "Why did the Minecraft player go to the bank? Because he heard there was money in mining!",
  "How do Minecraft players stay in touch? Through the Nether!",
  "Why don't Minecraft players ever get bored? Because there's always something to mine!",
  "What do you call a Minecraft player who's always late? A respawner!",
  "Why did the Minecraft player bring a shovel to dinner? Because he wanted to dig in!",
  "What's a Minecraft player's favorite drink? Block-uccino!",
  "Why do Minecraft players make good teachers? Because they know how to block irrelevant information!",
  "How many blocks does it take to build a Minecraft joke? Just block-tave!",
  "Why did the Minecraft player become a magician? Because he wanted to make things disappear... into his inventory!",
  "What do you call a Minecraft player who tells jokes? A block-umentary!",
  "Why do Minecraft creepers never win at hide and seek? Because they always get caught red-handed!",
  "What's a Minecraft player's favorite movie? The Block-buster!",
  "Why did the Minecraft player bring a rope to the meeting? Because he wanted to tie up loose ends!",
  "How do Minecraft players say goodbye? They log off!",
  "Why do Minecraft players never get lost in the forest? Because they always have a compass to guide them!",
  "What do you call a Minecraft player who builds with dirt? An Earth-y builder!",
  "Why did the Minecraft player become a chef? Because he wanted to cook with fire!",
  "What's a Minecraft player's favorite animal? A block-ade!",
  "Why do Minecraft players never run out of ideas? Because they always have a block of them!",
  "How do you know if a Minecraft player is telling the truth? Their story doesn't have any plot holes!",
  "Why did the Minecraft player bring an umbrella indoors? Because it was about to rain blocks!",
  "What do you call a Minecraft player who's always complaining? A whine-er!",
  "Why do Minecraft villagers make poor singers? Because they can only hrmm and huh!",
  "What's a Minecraft player's favorite type of weather? Snow-block storms!",
  "Why did the Minecraft player become a reporter? Because he wanted to cover the news in blocks!",
  "How do Minecraft players celebrate birthdays? With a cake... and lots of mining!",
  "Why do Minecraft players never feel left out? Because there's always room in the inventory!",
  "What do you call a Minecraft player who's always worried? An anxiety block!",
  "Why did the Minecraft player bring a mirror to the Nether? Because he wanted to reflect on his choices!",
  "What's a Minecraft player's favorite type of art? Pixel art!",
  "Why do Minecraft players make great detectives? Because they always investigate the blocks!",
  "How do you know if a Minecraft player is happy? They're grinning from block to block!",
  "Why did the Minecraft player bring a hammer to the software store? Because he wanted to download some blocks!",
  "What do you call a Minecraft player who's always tired? A sleepy miner!",
  "Why do Minecraft skeletons never win at sports? Because they have no guts!",
  "What's a Minecraft player's favorite type of transportation? A mine cart!",
  "Why did the Minecraft player become a lawyer? Because he wanted to defend his blocks!",
  "How do Minecraft players stay organized? They put everything in their inventory!",
  "Why do Minecraft players never get tired of mining? Because it's a never-ending story!",
  "What do you call a Minecraft player who builds underwater cities? A deep thinker!",
  "Why did the Minecraft player bring a thermometer to the Nether? To see how hot the lava really was!",
  "What's a Minecraft player's favorite type of clothing? Mining gear!",
  "Why do Minecraft players never lose at trivia? Because they always know the right blocks!",
  "How do you know if a Minecraft player is lying? They say they've never found diamonds!",
  "Why did the Minecraft player bring a camera to the cave? Because he wanted to capture the moment!",
  "What do you call a Minecraft player who's always making mistakes? A trial and error miner!",
  "Why do Minecraft players never give up? Because they always respawn!",
  "What's a Minecraft player's favorite type of vacation? A mining expedition!",
  "Why did the Minecraft player become a dentist? Because he wanted to work with blocks!",
  "How do Minecraft players stay healthy? They eat lots of pixel fruits!",
  "Why do Minecraft zombies never win at relationships? Because they're always dead inside!",
  "What do you call a Minecraft player who builds castles in the sky? An ambitious dreamer!",
  "Why did the Minecraft player bring a telescope to the End dimension? To see what's coming!",
  "What's a Minecraft player's favorite type of book? A block-buster!",
  "Why do Minecraft players never feel lonely in the cave? Because they have plenty of company!",
  "How do you know if a Minecraft player is brave? They venture into the Nether!",
  "Why did the Minecraft player bring a stethoscope to the mine? To check the health of the ore!",
  "What do you call a Minecraft player who's always rushing? A speedrunner!",
  "Why do Minecraft players never need a therapist? Because they can work out their issues by mining!",
  "What's a Minecraft player's favorite type of poem? A block-verse!",
  "Why did the Minecraft player become a photographer? Because he wanted to capture blocks!",
  "How do Minecraft players know they're growing up? When they start playing in survival mode!",
  "Why do Minecraft creepers never win at cooking shows? Because they always explode under pressure!",
  "What do you call a Minecraft player who's always quiet? A silent miner!",
  "Why did the Minecraft player bring a dictionary to the game? Because he wanted to expand his vocabulary... of blocks!",
  "What's a Minecraft player's favorite type of store? A block-buster store!",
  "Why do Minecraft players never need a dating service? Because they have plenty of blocks to choose from!",
  "How do you know if a Minecraft player is confident? They build without a blueprint!",
  "Why did the Minecraft player bring a GPS to the biome? Because he didn't want to get lost in the sauce!",
  "What do you call a Minecraft player who builds with wool? A woolly builder!",
  "Why do Minecraft players never feel poor? Because they have block wealth!",
  "What's a Minecraft player's favorite type of music festival? The Pixel Fest!",
  "Why did the Minecraft player become a hairstylist? Because he wanted to cut some blocks!",
  "How do Minecraft players stay connected? Through the server!",
  "Why do Minecraft zombies never win at school? Because they can't focus!",
  "What do you call a Minecraft player who's always researching? A curious miner!",
  "Why did the Minecraft player bring a flashcard to the dungeon? To study the mobs!",
  "What's a Minecraft player's favorite type of weather app? The block-cast!",
  "Why do Minecraft players never need a motivational speaker? Because they have their goals... literally built in!",
  "How do you know if a Minecraft player is artistic? They build amazing structures!",
  "Why did the Minecraft player bring a notebook to the cave? Because he wanted to take notes!",
  "What do you call a Minecraft player who's always experimenting? A curious cat... or should I say, curious cat mob!",
  "Why do Minecraft players never feel left behind? Because they always catch up!",
  "What's a Minecraft player's favorite type of game show? The Block and Roll!",
  "Why did the Minecraft player become a scientist? Because he wanted to study blocks!",
  "How do Minecraft players celebrate success? With a victory mine!",
  "Why do Minecraft skeletons never win at poker? Because they're too transparent!",
  "What do you call a Minecraft player who builds with intention? A purposeful builder!",
  "Why did the Minecraft player bring a workout routine to the mine? Because he wanted to get physically fit!",
  "What's a Minecraft player's favorite type of dessert? Block pudding!",
  "Why do Minecraft players never feel unmotivated? Because there's always another block to mine!",
  "How do you know if a Minecraft player is a true fan? They can speak the language of blocks!",
  "Why did the Minecraft player bring a telescope to the mountain? To see what's beyond the blocks!",
  "What do you call a Minecraft player who's always planning? A strategic builder!",
  "Why do Minecraft players never lose hope? Because they always respawn stronger!",
  "What's a Minecraft player's favorite type of currency? Blocks!",
  "Why did the Minecraft player become a tour guide? Because he wanted to show off his builds!",
  "How do Minecraft players handle stress? They go mining!",
  "Why do Minecraft creepers never win at surprise parties? Because they always explode the surprise!",
  "What do you call a Minecraft player who's always helping others? A supportive builder!",
  "Why did the Minecraft player bring a mirror to the Nether? To check if the lava was really that hot!",
  "What's a Minecraft player's favorite type of dance? The block dance!",
  "Why do Minecraft players never feel bored at home? Because they can play Minecraft!",
  "How do you know if a Minecraft player is determined? They never give up on their builds!",
  "Why did the Minecraft player bring a ruler to the cave? To measure the blocks!",
  "What do you call a Minecraft player who's always innovating? A creative builder!",
  "Why do Minecraft zombies never win at intelligence contests? Because they're mindless!",
  "What's a Minecraft player's favorite type of restaurant? The Block House!",
  "Why did the Minecraft player become a motivational speaker? Because he wanted to inspire blocks!",
  "How do Minecraft players stay productive? They set mining goals!",
  "Why do Minecraft players never feel isolated? Because they have the community!",
  "What do you call a Minecraft player who's always optimistic? A hopeful builder!",
  "Why did the Minecraft player bring a lantern to the End dimension? To light up his discoveries!",
  "What's a Minecraft player's favorite type of exercise? Mining squats!",
  "Why do Minecraft players never lose their sense of humor? Because blocks are hilarious!",
  "How do you know if a Minecraft player is passionate? They talk about building all day!",
  "Why did the Minecraft player bring a calculator to the ore farm? To count his riches!",
  "What do you call a Minecraft player who's always adventurous? An explorer!",
  "Why do Minecraft skeletons never win at dancing? Because they have no rhythm!",
  "What's a Minecraft player's favorite type of juice? Block juice!",
  "Why did the Minecraft player become a teacher? Because he wanted to educate about blocks!",
  "How do Minecraft players handle failure? They respawn and try again!",
  "Why do Minecraft players never feel underappreciated? Because their builds speak for themselves!",
  "What do you call a Minecraft player who's always learning? A student of the blocks!",
  "Why did the Minecraft player bring a thermometer to the cave? To check the temperature of the adventure!",
  "What's a Minecraft player's favorite type of game? Minecraft!",
  "Why do Minecraft players never lose their creativity? Because there's always another block to place!",
  "How do you know if a Minecraft player is skilled? Their builds are masterpieces!",
  "Why did the Minecraft player bring a journal to the biome? To document his journey!",
  "What do you call a Minecraft player who's always improving? A dedicated builder!",
  "Why do Minecraft creepers never win at hiding? Because they always leave a crater!",
  "What's a Minecraft player's favorite type of movie? A block-buster!",
  "Why did the Minecraft player become a philosopher? Because he wanted to think outside the box... I mean block!",
  "How do Minecraft players celebrate milestones? With a special build!",
  "Why do Minecraft zombies never win at chess? Because they don't have a strategy!",
  "What do you call a Minecraft player who's always happy? A joyful builder!",
  "Why did the Minecraft player bring a magnifying glass to the mine? To see the fine details!",
  "What's a Minecraft player's favorite type of coffee? Block-uccino!",
  "Why do Minecraft players never feel bored in the community? Because there's always something new to discuss!",
  "How do you know if a Minecraft player is a expert? They can build anything in their head!",
  "Why did the Minecraft player bring a flashlight to the cave? Because he didn't want to be in the dark!",
  "What do you call a Minecraft player who's always supportive? A friendly builder!",
  "Why do Minecraft players never lose their sense of wonder? Because every block has potential!",
  "What's a Minecraft player's favorite type of book genre? Fantasy... with blocks!",
  "Why did the Minecraft player become a architect? Because he wanted to design blocks!",
  "How do Minecraft players stay inspired? By exploring new blocks and biomes!",
  "Why do Minecraft skeletons never win at tag? Because they're too slow!",
  "What do you call a Minecraft player who's always resourceful? An efficient builder!",
  "Why did the Minecraft player bring a net to the water? To catch some fish for dinner!",
  "What's a Minecraft player's favorite type of weather? Clear skies with building weather!",
  "Why do Minecraft players never feel unsupported? Because the community has their back!",
  "How do you know if a Minecraft player is patient? They can wait for ore to respawn!",
  "Why did the Minecraft player bring binoculars to the mountain? To see what's on the horizon!",
  "What do you call a Minecraft player who's always kind? A compassionate builder!",
  "Why do Minecraft creepers never win at poker? Because they're always explosive!",
  "What's a Minecraft player's favorite type of snack? Pixel nuts!",
  "Why did the Minecraft player become a counselor? Because he understood the blocks' feelings!",
  "How do Minecraft players stay humble? By remembering they started with nothing!",
  "Why do Minecraft zombies never win at fashion? Because they always look dead!",
  "What do you call a Minecraft player who's always prepared? A ready builder!",
  "Why did the Minecraft player bring a compass to the biome? To always find his way home!",
  "What's a Minecraft player's favorite type of bird? A block-jays!",
  "Why do Minecraft players never feel disconnected? Because they're always on the server!",
  "How do you know if a Minecraft player is wise? They know when to mine and when to fight!",
  "Why did the Minecraft player bring a map to the cave? To chart the unknown territories!",
  "What do you call a Minecraft player who's always focused? A dedicated miner!",
  "Why do Minecraft skeletons never win at limbo? Because they're too rigid!",
  "What's a Minecraft player's favorite type of gym? The block gym!",
  "Why did the Minecraft player become a builder? Because blocks were his passion!",
  "How do Minecraft players maintain friendships? By playing together on the same server!",
  "Why do Minecraft players never feel like they've reached their limit? Because there's always more to build!",
  "What do you call a Minecraft player who's always curious? An explorer of blocks!",
  "Why did the Minecraft player bring a blanket to the cave? To stay warm while mining!",
  "What's a Minecraft player's favorite type of tree? A block tree!",
  "Why do Minecraft creepers never win at hide and seek? Because they explode when found!",
  "How do you know if a Minecraft player is humble? They give credit to other builders!",
  "Why did the Minecraft player bring a rope to the canyon? To rappel down safely!",
  "What do you call a Minecraft player who's always encouraging? A supportive friend!",
  "Why do Minecraft zombies never win at interviews? Because they can't articulate properly!",
  "What's a Minecraft player's favorite type of math? Block-gebra!",
  "Why did the Minecraft player become a farmer? Because he wanted to grow blocks!",
  "How do Minecraft players handle challenges? They tackle them head-on with a pickaxe!",
  "Why do Minecraft players never feel like outsiders? Because everyone speaks the language of blocks!",
  "What do you call a Minecraft player who's always thoughtful? A considerate builder!",
  "Why did the Minecraft player bring a notebook to the forest? To sketch his building ideas!",
  "What's a Minecraft player's favorite type of dessert? Cake-block!",
  "Why do Minecraft skeletons never win at basketball? Because they can't handle the pressure!",
  "How do you know if a Minecraft player is successful? When their builds get recognized!",
  "Why did the Minecraft player bring a shovel to the beach? To dig for treasure!",
  "What do you call a Minecraft player who's always respectful? A well-mannered builder!",
  "Why do Minecraft creepers never win at performances? Because they blow their chance!",
  "What's a Minecraft player's favorite type of sport? Block-ball!",
  "Why did the Minecraft player become a cook? Because he wanted to use the stove blocks!",
  "How do Minecraft players show appreciation? By visiting other builders' creations!",
  "Why do Minecraft zombies never win at communication? Because they only moan!",
  "What do you call a Minecraft player who's always positive? An optimistic builder!",
  "Why did the Minecraft player bring a flashlight to the End? To see the darkness clearly!",
  "What's a Minecraft player's favorite type of sandwich? A block sandwich!",
  "Why do Minecraft players never feel undervalued? Because every block they place matters!",
  "How do you know if a Minecraft player is a leader? They inspire others to build!",
  "Why did the Minecraft player bring a net to the ocean? To explore what's beneath!",
  "What do you call a Minecraft player who's always fair? An honorable builder!",
  "Why do Minecraft skeletons never win at negotiations? Because they can't make a deal!",
  "What's a Minecraft player's favorite type of art? Pixel art!",
  "Why did the Minecraft player become a historian? Because he wanted to study the history of blocks!",
  "How do Minecraft players stay motivated? By celebrating every achievement!",
  "Why do Minecraft players never feel alone? Because they have the community!",
  "What do you call a Minecraft player who's always humble? A modest builder!",
  "Why did the Minecraft player bring a telescope to the End dimension? To see the distant future!",
  "What's a Minecraft player's favorite type of flower? A block flower!",
  "Why do Minecraft creepers never win at competitions? Because they're too explosive!",
  "How do you know if a Minecraft player is passionate? They can talk about it for hours!",
  "Why did the Minecraft player bring a map to the dimension? To navigate the unknown!",
  "What do you call a Minecraft player who's always welcoming? A friendly host!",
  "Why do Minecraft zombies never win at debates? Because they don't have any brains!",
  "What's a Minecraft player's favorite type of game? A block-buster game!",
  "Why did the Minecraft player become a guide? Because he wanted to help others explore!",
  "How do Minecraft players support each other? By sharing tips and building together!",
  "Why do Minecraft players never feel like quitting? Because the game is endless!",
  "What do you call a Minecraft player who's always helping? A generous builder!",
  "Why did the Minecraft player bring a camera to the sky? To photograph the clouds!",
  "What's a Minecraft player's favorite type of clothing? Mining clothes!",
  "Why do Minecraft skeletons never win at sports competitions? Because they lack coordination!",
  "How do you know if a Minecraft player is talented? Their builds are incredibly detailed!",
  "Why did the Minecraft player bring a lantern to the cave system? To illuminate the darkness!",
  "What do you call a Minecraft player who's always kind-hearted? A loving builder!",
  "Why do Minecraft creepers never win at surprise parties? Because they spoil the surprise!",
  "What's a Minecraft player's favorite type of breakfast? Pixel pancakes!",
  "Why did the Minecraft player become a doctor? Because he wanted to cure block fever!",
  "How do Minecraft players celebrate victories? With a mining party!",
  "Why do Minecraft zombies never win at comedy shows? Because they can't be funny!",
  "What do you call a Minecraft player who's always reliable? A dependable builder!",
  "Why did the Minecraft player bring a rope to the fortress? To secure his position!",
  "What's a Minecraft player's favorite type of fish? A block fish!",
  "Why do Minecraft players never feel limited? Because the possibilities are endless!",
  "How do you know if a Minecraft player is dedicated? They play every single day!",
  "Why did the Minecraft player bring a shovel to the desert? To dig for ancient treasures!",
  "What do you call a Minecraft player who's always truthful? An honest builder!",
  "Why do Minecraft skeletons never win at races? Because they can't keep pace!",
  "What's a Minecraft player's favorite type of weather? Sunny building weather!",
  "Why did the Minecraft player become a musician? Because he wanted to play the note blocks!",
  "How do Minecraft players stay connected? Through online servers!",
  "Why do Minecraft players never feel unsupported? Because the community is always there!",
  "What do you call a Minecraft player who's always creative? An imaginative builder!",
  "Why did the Minecraft player bring a microscope to the cave? To examine the ore closely!",
  "What's a Minecraft player's favorite type of plant? A block plant!",
  "Why do Minecraft creepers never win at surprise reveals? Because they blow everything up!",
  "How do you know if a Minecraft player is patient? They can mine for hours!",
  "Why did the Minecraft player bring a notebook to the village? To take notes on trades!",
  "What do you call a Minecraft player who's always generous? A giving builder!",
  "Why do Minecraft zombies never win at intelligence tests? Because they're not very smart!",
  "What's a Minecraft player's favorite type of animal sound? A block moo!",
  "Why did the Minecraft player become a scientist? Because he wanted to study block physics!",
  "How do Minecraft players inspire each other? By sharing their amazing builds!",
  "Why do Minecraft players never feel bored? Because there's always something to create!",
  "What do you call a Minecraft player who's always supportive? An uplifting builder!",
  "Why did the Minecraft player bring a lantern to the Nether? To light up the darkness!",
  "What's a Minecraft player's favorite type of candy? Block candy!",
  "Why do Minecraft skeletons never win at social gatherings? Because they're boring!",
  "How do you know if a Minecraft player is experienced? Their builds show advanced techniques!",
  "Why did the Minecraft player bring a map to the End? To navigate the endgame!",
  "What do you call a Minecraft player who's always encouraging? A motivating builder!",
  "Why do Minecraft creepers never win at trust exercises? Because they're unreliable!",
  "What's a Minecraft player's favorite type of homework? Math about blocks!",
  "Why did the Minecraft player become a philosopher? Because he pondered the meaning of blocks!",
  "How do Minecraft players celebrate milestones? With a special build or achievement!",
  "Why do Minecraft zombies never win at job interviews? Because they lack qualifications!",
  "What do you call a Minecraft player who's always respectful? A courteous builder!",
  "Why did the Minecraft player bring a flashcard to the dungeon? To study mob behaviors!",
  "What's a Minecraft player's favorite type of drink? Block juice!",
  "Why do Minecraft players never feel disconnected? Because they're all mining the same game!",
  "How do you know if a Minecraft player is creative? Their builds are unique!",
  "Why did the Minecraft player bring a backpack to the mine? To carry more blocks!",
  "What do you call a Minecraft player who's always positive? An upbeat builder!",
  "Why do Minecraft skeletons never win at hide and seek? Because their bones rattle!",
  "What's a Minecraft player's favorite type of sport? Mining ball!",
  "Why did the Minecraft player become a teacher? Because he wanted to educate about blocks!",
  "How do Minecraft players handle setbacks? They respawn and try again!",
  "Why do Minecraft players never feel unsuccessful? Because every block placed is a success!",
  "What do you call a Minecraft player who's always thoughtful? A considerate friend!",
  "Why did the Minecraft player bring a compass to the cave? To always find his way back!",
  "What's a Minecraft player's favorite type of tree? A block tree!",
  "Why do Minecraft creepers never win at emotional control? Because they explode easily!",
  "How do you know if a Minecraft player is serious? They play in hardcore mode!",
  "Why did the Minecraft player bring a pickaxe to the office? To break through challenges!",
  "What do you call a Minecraft player who's always reliable? A trustworthy builder!",
  "Why do Minecraft zombies never win at competitions? Because they're too slow!",
  "What's a Minecraft player's favorite type of music? Block and roll!",
  "Why did the Minecraft player become a architect? Because he wanted to design amazing structures!",
  "How do Minecraft players support the community? By sharing their knowledge and creations!",
  "Why do Minecraft players never feel bored? Because Minecraft is never boring!",
  "What do you call a Minecraft player who's always cheerful? A happy builder!",
  "Why did the Minecraft player bring a journal to the biome? To document discoveries!",
  "What's a Minecraft player's favorite type of dessert? Block cake!",
  "Why do Minecraft skeletons never win at talent shows? Because they have no substance!",
  "How do you know if a Minecraft player is wise? They balance work and play!",
  "Why did the Minecraft player bring a net to the water? To catch fish for food!",
  "What do you call a Minecraft player who's always kind? A compassionate friend!",
  "Why do Minecraft creepers never win at stealth missions? Because they explode!",
  "What's a Minecraft player's favorite type of game? A sandbox game!",
  "Why did the Minecraft player become a builder? Because building is his passion!",
  "How do Minecraft players celebrate achievements? With a party in their world!",
  "Why do Minecraft zombies never win at anything? Because they're lifeless!",
  "What do you call a Minecraft player who's always determined? A persistent builder!",
  "Why did the Minecraft player bring a telescope to the mountain? To see the future!",
  "What's a Minecraft player's favorite type of flower? A dandelion block!",
  "Why do Minecraft players never feel limited? Because blocks have no limits!",
  "How do you know if a Minecraft player is passionate? They play in their sleep!",
  "Why did the Minecraft player bring a map to the fortress? To plan his strategy!",
  "What do you call a Minecraft player who's always fair? An impartial builder!",
  "Why do Minecraft skeletons never win at dancing? Because they have no rhythm!",
  "What's a Minecraft player's favorite type of cuisine? Block cuisine!",
  "Why did the Minecraft player become a explorer? Because he wanted to discover new blocks!",
  "How do Minecraft players stay inspired? By exploring and creating together!",
  "Why do Minecraft players never feel unsupported? Because everyone helps everyone!",
  "What do you call a Minecraft player who's always honest? A truthful builder!",
  "Why did the Minecraft player bring a lantern to the fortress? To see in the darkness!",
  "What's a Minecraft player's favorite type of sport? Block sports!",
  "Why do Minecraft creepers never win at trust? Because they explode unexpectedly!",
  "How do you know if a Minecraft player is experienced? They can navigate any biome!",
  "Why did the Minecraft player bring a notebook to the farm? To track his crops!",
  "What do you call a Minecraft player who's always encouraging? A supportive friend!",
  "Why do Minecraft zombies never win at arguments? Because they have no points!",
  "What's a Minecraft player's favorite type of pizza? Block pizza!",
  "Why did the Minecraft player become a scientist? Because he wanted to study blocks!",
  "How do Minecraft players celebrate success? By sharing their achievements!",
  "Why do Minecraft players never feel left out? Because everyone is welcome!",
  "What do you call a Minecraft player who's always respectful? A well-mannered friend!",
  "Why did the Minecraft player bring a flashlight to the End? To see the darkness!",
  "What's a Minecraft player's favorite type of gem? A block gem!",
  "Why do Minecraft skeletons never win at listening? Because they can't hear!",
  "How do you know if a Minecraft player is skilled? Their buildings are masterpieces!",
  "Why did the Minecraft player bring a rope to the canyon? To climb safely!",
  "What do you call a Minecraft player who's always generous? A giving friend!",
  "Why do Minecraft creepers never win at parties? Because they blow them up!",
  "What's a Minecraft player's favorite type of game mode? Survival!",
  "Why did the Minecraft player become a guide? Because he wanted to help others!",
  "How do Minecraft players handle challenges? By mining through them!",
  "Why do Minecraft zombies never win at anything? Because they're undead!",
  "What do you call a Minecraft player who's always positive? An optimistic friend!",
  "Why did the Minecraft player bring a camera to the build? To capture the moment!",
  "What's a Minecraft player's favorite type of tree? A birch block tree!",
  "Why do Minecraft players never feel bored? Because there's always more to do!",
  "How do you know if a Minecraft player is dedicated? They never miss a day!",
  "Why did the Minecraft player bring a map to the village? To find all the traders!",
  "What do you call a Minecraft player who's always kind-hearted? A loving friend!",
  "Why do Minecraft skeletons never win at negotiations? Because they can't make a deal!",
  "What's a Minecraft player's favorite type of song? A block song!",
  "Why did the Minecraft player become a farmer? Because he wanted to grow blocks!",
  "How do Minecraft players support the community? By helping other players!",
  "Why do Minecraft players never feel unsuccessful? Because every effort matters!",
  "What do you call a Minecraft player who's always focused? A dedicated builder!",
  "Why did the Minecraft player bring a notebook to the cave? To map out the tunnels!",
  "What's a Minecraft player's favorite type of food? Block food!",
  "Why do Minecraft creepers never win at relationships? Because they're too explosive!",
  "How do you know if a Minecraft player is wise? They know when to fight and when to flee!",
  "Why did the Minecraft player bring a lantern to the village? To see the traders!",
  "What do you call a Minecraft player who's always helpful? A kind-hearted friend!",
  "Why do Minecraft zombies never win at games? Because they're not intelligent!",
  "What's a Minecraft player's favorite type of juice? Orange block juice!",
  "Why did the Minecraft player become a teacher? Because he wanted to inspire builders!",
  "How do Minecraft players stay motivated? By reaching new goals!",
  "Why do Minecraft players never feel isolated? Because the community is huge!",
  "What do you call a Minecraft player who's always creative? An imaginative friend!",
  "Why did the Minecraft player bring a rope to the mine? To stay safe while climbing!",
  "What's a Minecraft player's favorite type of sport? Block ball!",
  "Why do Minecraft skeletons never win at races? Because they're too slow!",
  "How do you know if a Minecraft player is passionate? They dream about blocks!",
  "Why did the Minecraft player bring a flashcard to the biome? To study the terrain!",
  "What do you call a Minecraft player who's always honest? A truthful friend!",
  "Why do Minecraft creepers never win at performances? Because they explode on stage!",
  "What's a Minecraft player's favorite type of meal? A block meal!",
  "Why did the Minecraft player become a explorer? Because he wanted to find new treasures!",
  "How do Minecraft players celebrate? By building something amazing!",
  "Why do Minecraft players never feel uncertain? Because blocks are solid!",
  "What do you call a Minecraft player who's always supportive? An uplifting friend!",
  "Why did the Minecraft player bring a map to the End? To navigate the endgame!",
  "What's a Minecraft player's favorite type of animal? A block animal!",
  "Why do Minecraft zombies never win at anything? Because they're not equipped!",
  "How do you know if a Minecraft player is experienced? They never get lost!",
  "Why did the Minecraft player bring a telescope to the top of a tower? To see the world!",
  "What do you call a Minecraft player who's always encouraging? A supportive builder!",
  "Why do Minecraft skeletons never win at hide and seek? Because they rattle!",
  "What's a Minecraft player's favorite type of book? A block book!",
  "Why did the Minecraft player become a musician? Because he wanted to play the note blocks!",
  "How do Minecraft players stay connected? By playing together!",
  "Why do Minecraft players never feel disconnected? Because they're all on the same server!",
  "What do you call a Minecraft player who's always loyal? A faithful friend!",
  "Why did the Minecraft player bring a flashlight to the End dimension? To see the darkness!",
  "What's a Minecraft player's favorite type of weather? Clear skies for building!",
  "Why do Minecraft creepers never win at hide and seek? Because they blow their cover!",
  "How do you know if a Minecraft player is talented? Their builds are incredible!",
  "Why did the Minecraft player bring a journal to the desert? To sketch the landscape!",
  "What do you call a Minecraft player who's always thoughtful? A considerate friend!",
  "Why do Minecraft zombies never win at competitions? Because they're too slow and dumb!",
  "What's a Minecraft player's favorite type of drink? Block water!",
  "Why did the Minecraft player become a philosopher? Because he thought about blocks!",
  "How do Minecraft players inspire others? By creating amazing builds!",
  "Why do Minecraft players never feel bored with the game? Because there's always more to create!",
  "What do you call a Minecraft player who's always cheerful? A happy friend!",
  "Why did the Minecraft player bring a shovel to the mountain? To dig for resources!",
  "What's a Minecraft player's favorite type of tree? A dark oak block tree!",
  "Why do Minecraft skeletons never win at relationships? Because they have no heart!",
  "How do you know if a Minecraft player is determined? They never give up on a build!",
  "Why did the Minecraft player bring a net to the sky? To catch the clouds!",
  "What do you call a Minecraft player who's always kind? A compassionate friend!",
  "Why do Minecraft creepers never win at stealth? Because they're too explosive!",
  "What's a Minecraft player's favorite type of song? A mining song!",
  "Why did the Minecraft player become a doctor? Because he wanted to heal the wounded!",
  "How do Minecraft players support each other? By sharing resources!",
  "Why do Minecraft players never feel unsuccessful? Because failure is just learning!",
  "What do you call a Minecraft player who's always helpful? A helpful friend!",
  "Why did the Minecraft player bring a compass to the End? To find the way back!",
  "What's a Minecraft player's favorite type of flower? A rose block!",
  "Why do Minecraft zombies never win at anything? Because they lack the skills!",
  "How do you know if a Minecraft player is skilled? They build in any biome!",
  "Why did the Minecraft player bring a lantern to the cave? To light his path!",
  "What do you call a Minecraft player who's always positive? A positive friend!",
  "Why do Minecraft skeletons never win at talent shows? Because they're not talented!",
  "What's a Minecraft player's favorite type of meal? A roasted block meal!",
  "Why did the Minecraft player become a builder? Because building is his life!",
  "How do Minecraft players celebrate victories? With a grand feast!",
  "Why do Minecraft players never feel alone? Because other players are always around!",
  "What do you call a Minecraft player who's always fair? A fair friend!",
  "Why did the Minecraft player bring a map to the biome? To explore safely!",
  "What's a Minecraft player's favorite type of animal? A diamond block animal!",
  "Why do Minecraft creepers never win at anything? Because they self-destruct!",
  "How do you know if a Minecraft player is brave? They explore the Nether!",
  "Why did the Minecraft player bring a rope to the fortress? To climb the walls!",
  "What do you call a Minecraft player who's always honest? An honest friend!",
  "Why do Minecraft zombies never win at games? Because they can't focus!",
  "What's a Minecraft player's favorite type of transportation? A mine cart!",
  "Why did the Minecraft player become a scientist? Because he loved studying blocks!",
  "How do Minecraft players handle challenges? By mining through them strategically!",
  "Why do Minecraft players never feel bored? Because imagination is unlimited!",
  "What do you call a Minecraft player who's always encouraging? An encouraging friend!",
  "Why did the Minecraft player bring a flashcard to the ocean? To learn about fish!",
  "What's a Minecraft player's favorite type of gem? An emerald block!",
  "Why do Minecraft skeletons never win at anything? Because they lack coordination!",
  "How do you know if a Minecraft player is experienced? They know all the biomes!",
  "Why did the Minecraft player bring a notebook to the End dimension? To record his discoveries!",
  "What do you call a Minecraft player who's always generous? A generous friend!",
  "Why do Minecraft creepers never win at trust exercises? Because they blow them!",
  "What's a Minecraft player's favorite type of cuisine? Block cuisine!",
  "Why did the Minecraft player become a guide? Because he loved helping others explore!",
  "How do Minecraft players celebrate achievements? With a party and a new build!",
  "Why do Minecraft players never feel unsuccessful? Because they achieve daily!",
  "What do you call a Minecraft player who's always supportive? A supportive friend!",
  "Why did the Minecraft player bring a lantern to the fortress? To navigate the darkness!",
  "What's a Minecraft player's favorite type of music? Mine craft music!",
  "Why do Minecraft zombies never win at anything? Because they're not smart!",
  "How do you know if a Minecraft player is talented? They create masterpieces!",
  "Why did the Minecraft player bring a camera to the sunset? To capture the beauty!",
  "What do you call a Minecraft player who's always kind? A kind friend!",
  "Why do Minecraft skeletons never win at races? Because they can't keep pace!",
  "What's a Minecraft player's favorite type of plant? A block plant!",
  "Why did the Minecraft player become a farmer? Because he wanted to grow and harvest!",
  "How do Minecraft players inspire the community? By sharing their creations!",
  "Why do Minecraft players never feel bored? Because there's always more to mine!",
  "What do you call a Minecraft player who's always cheerful? A cheerful friend!",
  "Why did the Minecraft player bring a shovel to the beach? To dig for treasure!",
  "What's a Minecraft player's favorite type of candy? A sweet block!",
  "Why do Minecraft creepers never win at anything? Because they're self-destructive!",
  "How do you know if a Minecraft player is wise? They know when to mine and when to fight!",
  "Why did the Minecraft player bring a rope to the mountain? For safety while climbing!",
  "What do you call a Minecraft player who's always loyal? A loyal friend!",
  "Why do Minecraft zombies never win at intelligence? Because they have no brains!",
  "What's a Minecraft player's favorite type of food? Block food!",
  "Why did the Minecraft player become a teacher? Because he wanted to teach others!",
  "How do Minecraft players handle failure? By respawning and trying again!",
  "Why do Minecraft players never feel unsuccessful? Because they learn from every experience!",
  "What do you call a Minecraft player who's always helpful? A helpful friend!",
  "Why did the Minecraft player bring a map to the fortress? To plan his strategy!",
  "What's a Minecraft player's favorite type of tree? A spruce block tree!",
  "Why do Minecraft skeletons never win at anything? Because they're not equipped!",
  "How do you know if a Minecraft player is passionate? They never stop playing!",
  "Why did the Minecraft player bring a flashcard to the End? To study the mobs!",
  "What do you call a Minecraft player who's always respectful? A respectful friend!",
  "Why do Minecraft creepers never win at surprises? Because they always spoil them!",
  "What's a Minecraft player's favorite type of song? A block-busting song!",
  "Why did the Minecraft player become a architect? Because he wanted to design!",
  "How do Minecraft players stay motivated? By setting new goals!",
  "Why do Minecraft players never feel isolated? Because the community is welcoming!",
  "What do you call a Minecraft player who's always creative? A creative friend!",
  "Why did the Minecraft player bring a lantern to the cave system? To illuminate it!",
  "What's a Minecraft player's favorite type of sport? Block sport!",
  "Why do Minecraft zombies never win at anything? Because they're too slow!",
  "How do you know if a Minecraft player is skilled? Their builds are detailed!",
  "Why did the Minecraft player bring a telescope to the mountain? To see afar!",
  "What do you call a Minecraft player who's always honest? An honest friend!",
  "Why do Minecraft skeletons never win at competitions? Because they lack strength!",
  "What's a Minecraft player's favorite type of drink? A block drink!",
  "Why did the Minecraft player become a explorer? Because he wanted to discover!",
  "How do Minecraft players celebrate? By building something awesome!",
  "Why do Minecraft players never feel stuck? Because they can always dig their way out!",
  "What do you call a Minecraft player who's always encouraging? An encouraging friend!",
  "Why did the Minecraft player bring a journal to the biome? To document everything!",
  "What's a Minecraft player's favorite type of animal? A block animal!",
  "Why do Minecraft creepers never win at anything? Because they self-destruct every time!",
  "How do you know if a Minecraft player is experienced? They explore without fear!",
  "Why did the Minecraft player bring a net to the water? To catch what's beneath!",
  "What do you call a Minecraft player who's always supportive? A supportive friend!",
  "Why do Minecraft zombies never win at anything? Because they're not intelligent!",
  "What's a Minecraft player's favorite type of weather? Perfect building weather!",
  "Why did the Minecraft player become a musician? Because he loved note blocks!",
  "How do Minecraft players support the community? By sharing knowledge!",
  "Why do Minecraft players never feel unsuccessful? Because every block counts!",
  "What do you call a Minecraft player who's always thoughtful? A thoughtful friend!",
  "Why did the Minecraft player bring a compass to the desert? To navigate!",
  "What's a Minecraft player's favorite type of flower? A sunflower block!",
  "Why do Minecraft skeletons never win at anything? Because they're not intelligent!",
  "How do you know if a Minecraft player is determined? They build every day!",
  "Why did the Minecraft player bring a flashcard to the village? To learn about trades!",
  "What do you call a Minecraft player who's always kind? A kind friend!",
  "Why do Minecraft creepers never win at anything? Because they're unreliable!",
  "What's a Minecraft player's favorite type of meal? A balanced meal!",
  "Why did the Minecraft player become a farmer? Because he wanted to grow!",
  "How do Minecraft players inspire others? By sharing their passion!",
  "Why do Minecraft players never feel bored? Because blocks are always interesting!",
  "What do you call a Minecraft player who's always cheerful? A cheerful friend!",
  "Why did the Minecraft player bring a shovel to the forest? To dig for ore!",
  "What's a Minecraft player's favorite type of book? A block book!",
  "Why do Minecraft zombies never win at relationships? Because they're not alive!",
  "How do you know if a Minecraft player is skilled? They build without errors!",
  "Why did the Minecraft player bring a rope to the cliff? For safety!",
  "What do you call a Minecraft player who's always loyal? A loyal friend!",
  "Why do Minecraft skeletons never win at anything? Because they're weak!",
  "What's a Minecraft player's favorite type of tree? A jungle block tree!",
  "Why did the Minecraft player become a scientist? Because he wanted to discover!",
  "How do Minecraft players celebrate success? By sharing their victory!",
  "Why do Minecraft players never feel alone? Because they have the community!",
  "What do you call a Minecraft player who's always fair? A fair friend!",
  "Why did the Minecraft player bring a map to the ocean? To explore safely!",
  "What's a Minecraft player's favorite type of animal? An ender block animal!",
  "Why do Minecraft creepers never win at anything? Because they're destructive!",
  "How do you know if a Minecraft player is brave? They venture into dark caves!",
  "Why did the Minecraft player bring a lantern to the End? To see clearly!",
  "What do you call a Minecraft player who's always helpful? A helpful friend!",
  "Why do Minecraft zombies never win at anything? Because they lack skills!",
  "What's a Minecraft player's favorite type of furniture? Block furniture!",
  "Why did the Minecraft player become a builder? Because it's his passion!",
  "How do Minecraft players handle challenges? By mining through them!",
  "Why do Minecraft players never feel stuck? Because they can always respawn!",
  "What do you call a Minecraft player who's always positive? A positive friend!",
  "Why did the Minecraft player bring a flashcard to the cave? To study ores!",
  "What's a Minecraft player's favorite type of gem? A diamond!",
  "Why do Minecraft skeletons never win at anything? Because they're not smart!",
  "How do you know if a Minecraft player is experienced? They know all the tricks!",
  "Why did the Minecraft player bring a notebook to the farm? To track progress!",
  "What do you call a Minecraft player who's always generous? A generous friend!",
  "Why do Minecraft creepers never win at anything? Because they blow up!",
  "What's a Minecraft player's favorite type of cuisine? Block cuisine!",
  "Why did the Minecraft player become a guide? Because he loved teaching!",
  "How do Minecraft players celebrate achievements? With fireworks!",
  "Why do Minecraft players never feel unsuccessful? Because they never quit!",
  "What do you call a Minecraft player who's always supportive? A supportive friend!",
  "Why did the Minecraft player bring a lantern to the fortress? To light the way!",
  "What's a Minecraft player's favorite type of music? Minecraft soundtrack!",
  "Why do Minecraft zombies never win at anything? Because they're too dumb!",
  "How do you know if a Minecraft player is talented? They build masterpieces!",
  "Why did the Minecraft player bring a camera to the build? To record it!",
  "What do you call a Minecraft player who's always kind? A kind friend!",
  "Why do Minecraft skeletons never win at anything? Because they're too slow!",
  "What's a Minecraft player's favorite type of plant? A block plant!",
  "Why did the Minecraft player become a farmer? Because he wanted to grow crops!",
  "How do Minecraft players inspire the community? By creating amazing things!",
  "Why do Minecraft players never feel bored? Because there's always something new!",
  "What do you call a Minecraft player who's always cheerful? A cheerful friend!",
  "Why did the Minecraft player bring a shovel to the grassland? To dig for resources!",
  "What's a Minecraft player's favorite type of sweet? A block sweet!",
  "Why do Minecraft creepers never win at anything? Because they're too explosive!",
  "How do you know if a Minecraft player is wise? They balance fun and survival!",
  "Why did the Minecraft player bring a rope to the ravine? To climb safely!",
  "What do you call a Minecraft player who's always loyal? A loyal friend!",
  "Why do Minecraft zombies never win at anything? Because they lack brains!",
  "What's a Minecraft player's favorite type of food? Minecraft food!",
  "Why did the Minecraft player become a teacher? Because he wanted to inspire!",
  "How do Minecraft players handle setbacks? By respawning and continuing!",
  "Why do Minecraft players never feel unsuccessful? Because they always succeed eventually!",
  "What do you call a Minecraft player who's always helpful? A helpful friend!",
  "Why did the Minecraft player bring a map to the fortress? To find the treasure!",
  "What's a Minecraft player's favorite type of tree? A block tree!",
  "Why do Minecraft skeletons never win at anything? Because they're powerless!",
  "How do you know if a Minecraft player is passionate? They play constantly!",
  "Why did the Minecraft player bring a flashcard to the water? To study fishing!",
  "What do you call a Minecraft player who's always respectful? A respectful friend!",
  "Why do Minecraft creepers never win at anything? Because they're self-defeating!",
  "What's a Minecraft player's favorite type of song? A catchy block song!",
  "Why did the Minecraft player become an architect? Because he wanted to design!",
  "How do Minecraft players stay motivated? By pursuing new challenges!",
  "Why do Minecraft players never feel isolated? Because they're part of a community!",
  "What do you call a Minecraft player who's always creative? A creative friend!",
  "Why did the Minecraft player bring a lantern to the mine? To light the darkness!",
  "What's a Minecraft player's favorite type of sport? Minecraft sports!",
  "Why do Minecraft zombies never win at anything? Because they're mindless!",
  "How do you know if a Minecraft player is skilled? They build perfectly!",
  "Why did the Minecraft player bring a telescope to the peak? To see the world!",
  "What do you call a Minecraft player who's always honest? An honest friend!",
  "Why do Minecraft skeletons never win at anything? Because they're bones!",
  "What's a Minecraft player's favorite type of drink? A refreshing block drink!",
  "Why did the Minecraft player become an explorer? Because he wanted to discover!",
  "How do Minecraft players celebrate? By sharing their joy with others!",
  "Why do Minecraft players never feel stuck? Because they can dig through anything!",
  "What do you call a Minecraft player who's always encouraging? An encouraging friend!",
  "Why did the Minecraft player bring a journal to the forest? To document discoveries!",
  "What's a Minecraft player's favorite type of animal? A block-shaped animal!",
  "Why do Minecraft creepers never win at anything? Because they're destructive forces!",
  "How do you know if a Minecraft player is experienced? They explore everything!",
  "Why did the Minecraft player bring a net to the sky? To catch dreams!",
  "What do you call a Minecraft player who's always supportive? A supportive friend!",
  "Why do Minecraft zombies never win at anything? Because they lack everything!",
  "What's a Minecraft player's favorite type of weather? Clear skies for building!",
  "Why did the Minecraft player become a musician? Because he loved music!",
  "How do Minecraft players support the community? By helping fellow players!",
  "Why do Minecraft players never feel unsuccessful? Because success is constant!",
  "What do you call a Minecraft player who's always thoughtful? A thoughtful friend!",
  "Why did the Minecraft player bring a compass to the cave? To find the way!",
  "What's a Minecraft player's favorite type of flower? A beautiful block flower!",
  "Why do Minecraft skeletons never win at anything? Because they're just bones!",
  "How do you know if a Minecraft player is determined? They never give up!",
  "Why did the Minecraft player bring a flashcard to the End? To study the dragon!",
  "What do you call a Minecraft player who's always kind? A kind friend!",
  "Why do Minecraft creepers never win at anything? Because they're unreliable!",
  "What's a Minecraft player's favorite type of meal? A satisfying block meal!",
  "Why did the Minecraft player become a farmer? Because he loved nature!",
  "How do Minecraft players inspire others? By doing amazing things!",
  "Why do Minecraft players never feel bored? Because blocks are infinite!",
  "What do you call a Minecraft player who's always cheerful? A cheerful friend!",
  "Why did the Minecraft player bring a shovel to the mountain? To mine for ore!",
  "What's a Minecraft player's favorite type of candy? A tasty block candy!",
  "Why do Minecraft zombies never win at anything? Because they're not capable!",
  "How do you know if a Minecraft player is skilled? They know all the blocks!",
  "Why did the Minecraft player bring a rope to the tower? For security!",
  "What do you call a Minecraft player who's always loyal? A loyal friend!",
  "Why do Minecraft skeletons never win at anything? Because they're weak!",
  "What's a Minecraft player's favorite type of furniture? Block furniture!",
  "Why did the Minecraft player become a teacher? Because he loved sharing knowledge!",
  "How do Minecraft players handle challenges? By mining forward!",
  "Why do Minecraft players never feel unsuccessful? Because they keep trying!",
  "What do you call a Minecraft player who's always helpful? A helpful friend!",
  "Why did the Minecraft player bring a map to the biome? To explore!",
  "What's a Minecraft player's favorite type of tree? A beautiful block tree!",
  "Why do Minecraft creepers never win at anything? Because they're destructive!",
  "How do you know if a Minecraft player is brave? They explore the Nether without fear!",
  "Why did the Minecraft player bring a lantern to the fortress? To light it up!",
  "What do you call a Minecraft player who's always helpful? A helpful friend!",
  "Why do Minecraft zombies never win at anything? Because they're not smart!",
  "What's a Minecraft player's favorite type of transportation? A mine cart ride!",
  "Why did the Minecraft player become a scientist? Because he loved discovery!",
  "How do Minecraft players handle challenges? By mining through them carefully!",
  "Why do Minecraft players never feel stuck? Because they can always respawn!",
  "What do you call a Minecraft player who's always positive? A positive friend!",
  "Why did the Minecraft player bring a flashcard to the ocean? To study fish!",
  "What's a Minecraft player's favorite type of gem? A shiny diamond!",
  "Why do Minecraft skeletons never win at anything? Because they're not equipped!",
  "How do you know if a Minecraft player is experienced? They're calm in any situation!",
  "Why did the Minecraft player bring a notebook to the cave? To map it out!",
  "What do you call a Minecraft player who's always generous? A generous friend!",
  "Why do Minecraft creepers never win at anything? Because they blow up everything!",
  "What's a Minecraft player's favorite type of cuisine? Delicious block cuisine!",
  "Why did the Minecraft player become a guide? Because he wanted to help!",
  "How do Minecraft players celebrate? By building something incredible!",
  "Why do Minecraft players never feel unsuccessful? Because they always achieve!",
  "What do you call a Minecraft player who's always supportive? A supportive friend!"
];

function generateJokes(){
    
    const randomindex = Math.floor(Math.random()*jokes.length);
    jokeEl.textContent = jokes[randomindex];
} 
