const jokeEl = document.getElementById("joke");
const jokeBtn = document.querySelector(".jokerbtn");

window.addEventListener("DOMContentLoaded", () => {
  if (jokeBtn) {
    jokeBtn.addEventListener("click", generateJokes);
  }
});

const jokes = [
  "Why don't scientists trust atoms? Because they make up everything!",
  "I told my wife she was drawing her eyebrows too high. She looked surprised.",
  "Why don’t skeletons fight each other? They don’t have the guts.",
  "What do you call fake spaghetti? An impasta.",
  "Why do cows wear bells? Because their horns don’t work.",
  "What did one wall say to the other wall? I’ll meet you at the corner.",
  "Why couldn’t the bicycle stand up by itself? It was two-tired.",
  "Why did the scarecrow win an award? Because he was outstanding in his field.",
  "I would avoid the sushi if I was you. It’s a little fishy.",
  "Want to hear a joke about construction? I’m still working on it.",
  "Why don’t eggs tell jokes? They’d crack each other up.",
  "Why did the math book look sad? Because it had too many problems.",
  "What do you call cheese that isn’t yours? Nacho cheese.",
  "Why can’t your nose be 12 inches long? Because then it would be a foot.",
  "What did the grape do when he got stepped on? Nothing but let out a little wine.",
  "I used to play piano by ear, but now I use my hands.",
  "I’m reading a book on anti-gravity. It’s impossible to put down.",
  "Did you hear about the guy who invented Lifesavers? He made a mint.",
  "I bought some shoes from a drug dealer. I don’t know what he laced them with, but I was tripping all day.",
  "I’m so good at sleeping, I can do it with my eyes closed.",
  "Why don’t some couples go to the gym? Because some relationships don’t work out.",
  "What do you call a factory that makes okay products? A satisfactory.",
  "Why did the coffee file a police report? It got mugged.",
  "How does a penguin build its house? Igloos it together.",
  "What’s brown and sticky? A stick.",
  "Why did the golfer bring two pairs of pants? In case he got a hole in one.",
  "What do you call a pile of cats? A meowtain.",
  "Why did the cookie go to the hospital? Because he felt crummy.",
  "What did the ocean say to the beach? Nothing, it just waved.",
  "Why did the tomato turn red? Because it saw the salad dressing.",
  "Why don’t seagulls fly over the bay? Because then they’d be bagels.",
  "Why did the banana go to the doctor? Because it wasn’t peeling well.",
  "What do you call an alligator in a vest? An investigator.",
  "Why are frogs so happy? Because they eat whatever bugs them.",
  "Why do bees have sticky hair? Because they use honeycombs.",
  "What do you call a bear with no teeth? A gummy bear.",
  "Why did the man run around his bed? To catch up on his sleep.",
  "How do you organize a space party? You planet.",
  "Why don’t oysters donate to charity? Because they’re shellfish.",
  "Why do ducks have feathers? To cover their butt quacks.",
  "Why did the picture go to jail? Because it was framed.",
  "Why can’t you hear a pterodactyl using the restroom? Because the P is silent.",
  "What did the janitor say when he jumped out of the closet? Supplies!",
  "Why did the bicycle fall over? Because it was two-tired.",
  "Why did the chicken join a band? Because it had the drumsticks.",
  "Why did the student eat his homework? Because the teacher told him it was a piece of cake.",
  "What do you call a dog magician? A labracadabrador.",
  "Why did the stadium get hot after the game? All the fans left.",
  "Why do fish live in salt water? Because pepper makes them sneeze.",
  "How do you make holy water? You boil the hell out of it.",
  "Why can’t you give Elsa a balloon? Because she will let it go.",
  "What’s orange and sounds like a parrot? A carrot.",
  "Why did Cinderella get kicked off the soccer team? Because she kept running away from the ball.",
  "What did one hat say to the other? Stay here, I’m going on ahead.",
  "What do you call a sleeping bull? A bulldozer.",
  "What’s red and bad for your teeth? A brick.",
  "How do you make a tissue dance? Put a little boogie in it.",
  "Why did the man put his money in the freezer? He wanted cold hard cash.",
  "Why don’t you ever see elephants hiding in trees? Because they’re so good at it.",
  "What did the zero say to the eight? Nice belt!",
  "Why was six afraid of seven? Because seven eight nine.",
  "Why did the golfer wear two pairs of pants? In case he got a hole in one.",
  "What did the big flower say to the little flower? Hi, bud!",
  "Why was the broom late? It over swept!",
  "Why do birds fly south for the winter? It’s faster than walking.",
  "What’s black and white and goes around and around? A penguin in a revolving door.",
  "Why do elephants never use computers? They’re afraid of the mouse.",
  "Why did the duck get a detention? For quacking jokes in class.",
  "How do cows stay up to date? They read the moos-paper.",
  "What’s a skeleton’s favorite instrument? The trom-bone.",
  "How do you catch a squirrel? Climb a tree and act like a nut.",
  "Why did the teddy bear say no to dessert? Because he was stuffed.",
  "Why did the frog take the bus to work? His car got toad.",
  "What’s a pirate’s favorite letter? You’d think it’s R but it be the C.",
  "Why was the computer cold? It left its Windows open.",
  "Why can’t pirates learn the alphabet? Because they always get lost at C.",
  "What’s the best thing about Switzerland? I don’t know, but the flag is a big plus.",
  "Why did the hipster burn his tongue? He drank coffee before it was cool.",
  "What did the buffalo say to his son when he left for college? Bison.",
  "Why can’t you trust an atom? Because they make up everything!",
  "Why was the calendar so popular? Because it had a lot of dates.",
  "Why did the mushroom get invited to the party? Because he was a fungi.",
  "What’s Forrest Gump’s password? 1forest1.",
  "Why don’t mountains get cold in the winter? They wear snowcaps.",
  "Why did the fish blush? Because it saw the ocean’s bottom.",
  "What do you call a belt made of watches? A waist of time.",
  "Why did the barber win the race? Because he knew all the shortcuts.",
  "Why did the computer squeak? Because someone stepped on its mouse.",
  "Why was the snowman looking through the carrots? He was picking his nose.",
  "Why did the baker go to therapy? Because he kneaded it.",
  "What do you call an elephant that doesn’t matter? An irrelephant.",
  "Why was the cat sitting on the computer? To keep an eye on the mouse.",
  "How does a scientist freshen her breath? With experi-mints.",
  "Why did the banana get so many dates? Because it had appeal.",
  "Why did the astronaut break up with his girlfriend? He needed space.",
  "Why did the dog sit in the shade? Because he didn’t want to be a hot dog.",
  "What kind of tree fits in your hand? A palm tree.",
  "What’s a cat’s favorite color? Purr-ple.",
  "What kind of music do mummies listen to? Wrap music.",
  "What does a cloud wear under his raincoat? Thunderwear.",
  "What do you get from a pampered cow? Spoiled milk.",
  "Why did the music teacher go to jail? Because she got caught with a high note.",
  "Why do giraffes have long necks? Because their feet stink.",
  "What does a spider’s bride wear? A webbing dress.",
  "Why do pancakes always win at baseball? They have the best batter.",
  "Why was the belt arrested? For holding up a pair of pants.",
  "What do you get when you cross a snowman and a vampire? Frostbite.",
  "Why did the man stare at the can of orange juice? Because it said concentrate.",
  "What kind of shoes do ninjas wear? Sneakers.",
  "Why don’t vampires have more friends? Because they are a pain in the neck.",
  "What did one plate say to the other plate? Lunch is on me.",
  "Why did the horse cross the road? To visit his neigh-bors.",
  "What do elves learn in school? The elf-abet.",
  "Why was the baby strawberry upset? Because his parents were in a jam.",
  "Why did the skeleton go to the party alone? He had no body to go with him.",
  "Why was the student’s report card wet? It was below C-level.",
  "What kind of lion never roars? A dandelion.",
  "What did the spider do on the computer? Made a website.",
  "What do you call a cow with two legs? Lean beef.",
  "What do you call a cow with no legs? Ground beef.",
  "Why was the broom so tired? It was always sweeping.",
  "Why did the golfer bring an extra shirt? In case he got a hole in one.",
  "Why did the mushroom always get invited? Because he’s a fungi.",
  "What’s green and sings? Elvis Parsley.",
  "What did one snowman say to the other? Do you smell carrots?",
  "Why did the skeleton stay home from the dance? He had no body to dance with.",
  "What kind of tree can fit in your hand? A palm tree.",
  "What did one toilet say to the other toilet? You look flushed.",
  "Why did the chicken go to the seance? To talk to the other side.",
  "What’s the smartest insect? A spelling bee.",
  "Why do vampires always seem sick? They’re always coffin.",
  "What did the stamp say to the envelope? Stick with me and we’ll go places.",
  "Why did the cookie cry? Because his mother was a wafer so long.",
  "Why did the banana go out with the prune? Because it couldn’t find a date.",
  "What’s a ghost’s favorite dessert? I scream.",
  "Why did the man get hit by a bike every day? He was stuck in a vicious cycle.",
  "Why do bakers work so hard? Because they knead dough.",
  "Why did the lion eat the tightrope walker? He wanted a well-balanced meal.",
  "What’s brown and hairy and wears sunglasses? A coconut on vacation.",
  "Why are ghosts bad at lying? Because they are too transparent.",
  "What’s a vampire’s favorite fruit? A blood orange.",
  "Why did the fish get bad grades? Because it was below sea level.",
  "Why don’t ghosts like rain? It dampens their spirits.",
  "What did one eye say to the other? Between you and me, something smells.",
  "Why can’t your hand be 12 inches long? Because then it would be a foot!",
  "Why did the cow jump over the moon? To get to the Milky Way.",
  "Why was the duck so funny? Because he always quacked jokes.",
  "What’s a pirate’s favorite exercise? The plank.",
  "Why did the grape stop rolling? It ran out of juice.",
  "What do ghosts serve for dessert? Ice scream.",
  "Why did the owl get invited everywhere? He was a hoot.",
  "Why do chickens sit on eggs? Because they don’t have chairs.",
  "Why did the jellybean go to school? To be a smartie.",
  "Why did the baker stop making donuts? He got tired of the hole thing."
];


function generateJokes(){
    
    const randomindex = Math.floor(Math.random()*jokes.length);
    jokeEl.textContent = jokes[randomindex];
} 